language: python
python:
  - "3.6"
  - "3.7"
addons:
  postgresql: "9.4"
services:
  - rabbitmq
  - postgresql
cache:
  - apt
  - pip
before_install:
  - sudo apt-get -qq update
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install -y postgresql-plpython-9.4
  - sudo /etc/init.d/postgresql start 9.4
  - psql -c "create user taiga with superuser createdb password 'taiga';" -U postgres
  - psql -c "create database taiga owner taiga;" -U postgres
install:
  - travis_retry pip install -r requirements.txt -r requirements-devel.txt
script:
  - coverage run --source=taiga --omit='*tests*,*commands*,*migrations*,*admin*,*.jinja,*dashboard*,*settings*,*wsgi*,*questions*,*documents*' -m pytest -v --tb=native --pythonwarnings=default
after_success:
  - coveralls
